export interface TaskDone {
    id?: number; // Optional as it will be generated by the server
    title: string;
    startDate: string; // Assuming date format is YYYY-MM-DD
    dueDate: string; // Assuming date format is YYYY-MM-DD
    priority: string;
    status: string;  }